version: 2

updates:
  # Grouped GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    groups:
      all-actions:
        patterns:
          - "*"

  # Grouped Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    groups:
      langchain:
        patterns:
          - "langchain*"
      all-backend-deps:
        patterns:
          - "*"

  # Grouped frontend npm dependencies (main app)
  - package-ecosystem: "npm"
    directory: "/code/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    groups:
      frontend-deps:
        patterns:
          - "*"

  # Grouped frontend npm dependencies (UI tests)
  - package-ecosystem: "npm"
    directory: "/tests/integration/ui"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    groups:
      frontend-deps:
        patterns:
          - "*"
